### ISSUE TITLE
DsHidMini Issue #332

### ISSUE THREAD

**Issue by tomrow** [nefarius/DsHidMini#337] opened 2024-04-12 20:19 UTC
- [x] I have searched open and closed issues for duplicates
            (This issue references another issue in another project https://github.com/nefarius/DsHidMini/issues/332 )
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------
My sincerest apologies for attempting communication in such a way and place. While I believe that this program may be at least partially at fault, DsHidMini issue report creation is limited to contributors only, so I can't post this there. Feel free to close this issue if you feel it is inappropriate or irrelevant.

### Bug description

Windows' DEVMGMT reports a timeout error when a Sixaxis controller is connected via USB.
It connected to my PC several times, via both USB and Bluetooth, but when configuring the software to emulate different protocols, the program failed each time to reset the controller, prompting the user to manually disconnect the controller.
After several disconnection cycles by connecting it via USB to disconnect it from Bluetooth, the DsHidMini program seemed to become stuck such that both the Bluetooth and USB devices would remain listed as connected in the system despite the USB cable being connected, but only the Bluetooth connection would receive controller input. This seemed to persist between restarts of the PC. (I had not checked DEVMGMT at this point.)

Next, I tried connecting it to another computer, which failed to display the controller in the DsHidMini configuration window. I checked it in DEVMGMT which displayed the timeout error. This persisted when I attached it back to the original machine. The controller would still connect via Bluetooth when connected to the PC via a cable.

I then tried to connect the Sixaxis controller to a PlayStation 3 console, which also did not respond, until I pushed the pinhole button on the back of the controller.
After this it also connected successfully again to the first PC over USB.
### Steps to reproduce

-Repeatedly attempt to disconnect the controller from Bluetooth by inserting the Mini USB cable 
**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
After several reconnections, the controller becomes unresponsive
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
The controller will connect successfully via USB and will not become unresponsive after multiple USB disconnection cycles

### Machine info

Windows 11 Version 23H2 build 22631.3447 AMD64
Controller Sixaxis CECHZC1E

### Any other helpful information

The Sixaxis device was plugged into a USB 3 port on the front panel of my PC. I am not sure of the make and model of my Bluetooth radio or USB controller(s), if you need this info please reply and I should be able to find this information.

**Comment by nefarius** [comment] 2024-04-12 20:34
There's a reason I disabled issue submission for non-contributors because recently nobody submits a proper bug reports where there's actually something included that can hint at something that is reproducible or a "real" bug, not just someone's system misbehaving. That's what the support resources are for to not pollute my issue trackers with stuff that can not be worked on since it doesn't describe a TODO in any useful way. 

Thanks for the detailed report, but IDK what to do with this information, it is too vague to work on anything in particular TBF and will just sit here until I eventually close it.

**Closed** 2024-04-15 13:17 UTC
